language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
before_script:
- sudo apt-get update -qq
# Install Apache
- sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl php5-gd > /dev/null
- sudo /etc/init.d/apache2 stop
- sudo sed -i -e "s,APACHE_RUN_USER=www-data,APACHE_RUN_USER=$USER,g" /etc/apache2/envvars
- sudo sed -i -e "s,APACHE_RUN_GROUP=www-data,APACHE_RUN_GROUP=$USER,g" /etc/apache2/envvars
- sudo chown -R $USER /var/lock/apache2
- sudo chown -R $USER:$USER /var/www
- ln -s $TRAVIS_BUILD_DIR/tests/ /var/www/tests
- sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
- sudo /etc/init.d/apache2 start
# Xvfb
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# Fluxbox
- sudo apt-get install fluxbox -y --force-yes
- fluxbox &
- sleep 3 # give fluxbox some time to start
- composer update

addons:
  sauce_connect:
    username: jensentech
    access_key:
      secure: "YatXTpRyhoXslYvEDsM+1bSFey7tZbUSTFvIdqBsxPnGv6IpUWPUHwkwacbiL7CfmXyBFa1naU2xID3cHzm6dcIILOjeL0EQSWsEUkOJ2UZ9/2akkYe0g3NGR6roAovJOfkt+uTlZaQ4D4jDKBKoaLhVwRBUO/wD2AG55p/hA4K+R/etbv20aouBqtHj+UOxpId9ChXTk+9JDG7JtpXr7T4zk/IfmB4eBbSwrxBqvhtMvGXfLlGzEnxmhx4jEd3nae/tk1yv1cmEe0OQJ/Dz0V9kgfZc++Kk/0wH85mtMPomRzoKbCthbGiS10fKiiltNJaTZ6TTUuIK9RJPxSzn2ZnsxHE5f7/cqxUtaeedn6hN32gi9B/2deL6P6j3fWfUcMtw2Pvmek9o7nGKsi7oKNau8ZEwt3SyWoB1ipHJICRjtnsf8snpgCkcyFeLAofCJF8DotQgHIR+v/TNj0YBmMCbHX1+SZvcq6eKlBkt/HPrflGRs/ZZoa6EaHoy0nLs9EbCHhC6xlF08FghKCRiduy9MWVAQtIqNwHMooG+CgoNXzuQKeCup0DBUz71j5j6Um21sQD8v1UGh0pTp6SHrqeYTtXghRiv2oc9LrxAU2gziYA+7n4p2QCvWXsACoM8Us+QAKjafdiudYZ76af27f5qJY8U0mRX/cvfi4oizks="

script:
- mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
- php vendor/bin/robo test:acceptance