language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
before_script:
- sudo apt-get update -qq
# Install Apache
- sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl php5-gd mutt > /dev/null
- sudo /etc/init.d/apache2 stop
- sudo sed -i -e "s,APACHE_RUN_USER=www-data,APACHE_RUN_USER=$USER,g" /etc/apache2/envvars
- sudo sed -i -e "s,APACHE_RUN_GROUP=www-data,APACHE_RUN_GROUP=$USER,g" /etc/apache2/envvars
- sudo chown -R $USER /var/lock/apache2
- sudo chown -R $USER:$USER /var/www
- ln -s $TRAVIS_BUILD_DIR/tests/ /var/www/tests
- sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
- sudo /etc/init.d/apache2 start
# Xvfb
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# Fluxbox
- sudo apt-get install fluxbox -y --force-yes
- fluxbox &
- sleep 3 # give fluxbox some time to start
- composer update
script:
- mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
- pwd
- php vendor/bin/robo test:acceptance
after_failure:
- php vendor/bin/robo send:email
env:
  global:
    - secure: ZGsU5ARw6Z7S+IYu17hakdO0RjU40QnNfsEj56QD2kbADMXu0oqL7ZH0r2ONNJbWDi4nY79VpsNzaAtMMGURfidgqYFoqWRGEQav+R5nspffjxMoq4AFWv22M4gshOWAPNh557m29oxNgEw76AWHWL5Q7S4gbWWuUTkAx5g1yOeo0E8o57M/vuWdDaEvynk+rTFIoaVboAweMxyd/ugwgqmaqQKmHtr1QYqHi5ZQTs2VOOj94qfyFXBy4Z6KXwHFNMF2MGxMMrSMAaZYwc4IDP1LMFGvCHG2vwRYLJyEQ1YsTeZ3L8XxElwFk9ED0BbwnvfPkesoGk+kdQGkl1yXkVRcVUigN+G1WH7qfxK19CKUvVBmyY/c9uILzJHwlK7IiMIWrQJSD/TDxXNV34iuvBuMYQyHaJtZMNWD2mDOI1V7TssXxyqhkYGUuNLibTm2p26Wvk0FmAR/V0sgBvnHaGZQzQgoauAsCdGoaj3sj9Wi+rzFyzIUVZzkDuuXhjKnz8vGoMAOJiouiK8npvFPwSLAFRJFoGbIowahjM8OWp5NQtW48IailblNi7GzRweAUnfyVIAbsFYS7Hxk0USwbBrVZ79Qj8mc9aChcn8YTKke1BGP6OKnxT/FlJwJd1uU7UqgfW0psj1W6fkR+QkRH8PnO/66hTjRgHM7zl/ySZU=
    - secure: TYV0+eBWYofyBb8DwjG/a+EMYlhSzlXA1Uy9NPyFNyb/HjAKMZ5cD5Fge1516B8zC9yM9envNcM4SeivCD6XZBIroiWiDVFK+o8CxqOie/VdO94unwHMoYaTQC9CKwiNypfyNkI4tharOh/U6xvxIlSmqKQFBHbKVUYgBaTvGHCGPHnin0c+tTP3zPwRVo/w101hgZ7aZLh5rltVW4vZ5Tvww/4uFbGFXOXmF6VMPhi8b20KBcgwlhnC2nufTIZdfhLUQ4PTv3L5VQ7yoVEtHxa8vgbcAQwmC4F+pNPRZS/bJ3trBr0Fg8gwoM3Bb2ZzU6GDIfVpxuOpAh88kcD6Hfen3PS6r3VgMTqjXhV+h0OaCvLZJsq/dvqs0uopk/RBIyYSZFUCEgEaocDo+R8NM0eRDbT/+p3PKkpSjU6wOgHyTJv9SGZlm8TjY6dD0N7bpE6FhCcXMBh+k5HaGGYpkZiW67A4S90mZqjTpBKCpmj0W6wS3MMGSYEfQTBBTLLpCaGeb4z/S3GGg3/q9n+T1/V1v+biVaF0dPtF3kddsxeoKClSxy+JqXUkA8fge4pnxu0TcA4Ri8PhuI+EWbHui2Y0xPYP4wdpJiWaBWig9+85GvtVtRjptuXaAJRhHy1waqt01aeBfTSKYPYypMPYDcDr7yLvgGR1roOU9jB79Zg=
